### ISSUE TITLE
Change View rotates through the 4th dimension

### ISSUE THREAD

**Issue by thetaphi** [CometWolf/TurtleArchitectV2#1]
Test file "axis.TAb": http://pastebin.com/2cF7G5kc
CC 1.7, pack is AlienMC 1.2.9

That resulted in 
![2015-04-10_14 51 46](https://cloud.githubusercontent.com/assets/231587/7088033/34c8ee3a-df91-11e4-9e9f-3fd07b0cc1a4.png) (looking north).

The plan is rotated at least 90°, but that's only the start xD Try invoking "Change view" -> X -> Y -> Z -> X ... a few times. What I get is the visible axes always pointing right and down on the screen, but sometimes the center black block shows and sometimes it doesn't - in the same view. That means I'm looking at it once from below and once from above, but then the orientation of the other two axes should change. Clearly I'm trapped in a rotating hypercube.

Result: I have no clue how the Minecraft coordinates and the screen correlate any more. HALP!

**Comment by CometWolf** [comment]
To be honest the change view feature was never finished. I lost interest in MC shortly after it was functional enough for me to decorate the walls of my buildings 😛. Though, provided i understand you correctly, what you wise to acheive here could be accomplished by using the rotate feature in the blueprint menu.

**Comment by thetaphi** [comment]
Hm. I don't see a Rotate entry there, only Flip.

![2015-04-10_15 40 57](https://cloud.githubusercontent.com/assets/231587/7088909/07a8dc10-df98-11e4-836c-70c820420da9.png)

**Comment by CometWolf** [comment]
Ah, guess i must be mis-rembering. Anyways, I might get back to working on this in a couple of months or so, but for the moment it's dead Im afraid. You're free to tinker with it in the meantime yourself if you wish. The rotate feature is in classes/blueprint.Lua.

**Comment by thetaphi** [comment]
Alright :) As soon as I get tired of tinkering with EZ-NUKE I might get back to this. o/
